name: Compliance Gate
on: [pull_request]
jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: ./scripts/antiviolent-scanner.sh ${{ github.event.pull_request.head.sha }}
